blank_issues_enabled: false
contact_links:
  - name: Product Feature Request
    url: https://github.com/Dhananjay-latpate/RCMS/issues
    about: Provide feedback and ask for new features or enhancements!
  - name: Documentation Bug Report
    url: https://github.com/Dhananjay-latpate/RCMS/issues
    about: Create a report to help us improve the Resillix CMS documentation.
  - name: Documentation Request
    url: https://github.com/Dhananjay-latpate/RCMS/issues
    about: Create a request to add new information to the Resillix CMS documentation.
  - name: Resillix CMS Plugin SDK Bug Report
    url: https://github.com/Dhananjay-latpate/RCMS/issues
    about: Create a report to help us improve the Plugin SDK
  - name: Resillix CMS JS/TS SDK Bug Report
    url: https://github.com/Dhananjay-latpate/RCMS/issues
    about: Create a report to help us improve the JS/TS SDK
  - name: Resillix CMS Design System Bug Report
    url: https://github.com/Dhananjay-latpate/RCMS/issues
    about: Create a report to help us improve the Design System
  - name: Join the Community Discord
    url: https://github.com/Dhananjay-latpate/RCMS/discussions
    about: Come and interact with other community members!
